name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build docker image
        run: docker build -t rp-prod .

      - name: Lint code
        run: docker run --rm -t rp-prod cargo clippy --release -- -D warnings

      - name: Build for production
        run: docker run --rm -t rp-prod cargo build --release

    # - name: Run tests
    #   run: cargo test --verbose
    # Might add Hardware-In-The-Loop later
