name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup
      run: sudo apt install gcc-arm-none-eabi; rustup toolchain install nightly; rustup default nightly; rustup target add thumbv8m.main-none-eabihf

    - name: Build
      run: cargo build --verbose
    # - name: Run tests
    #   run: cargo test --verbose
    # Might add Hardware-In-The-Loop later
    
